apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
resources:
- ./namespace.yaml
helmCharts:
- name: cloudnative-pg
  namespace: cloudnative-pg
  releaseName: cloudnative-pg
  repo: https://cloudnative-pg.github.io/charts
  includeCRDs: true
  version: 0.22.0
